### ISSUE TITLE
Update to Next.js

### ISSUE THREAD

**Issue by jermbo** [jermbo/SampleAPIs#124]
Now that this system is running on React, we need to convert to as SSR platform. Next.js seems to be a popular option.

**Comment by jermbo** [comment]
Static site generation solves a couple major issues with the current version. SEO and Navigation. When trying to go to any api details page directly will result in a 404 error page. For example, go directly to this link, `https://sampleapis.com/api-list/avatar`. I think it would be very useful to have the ability to share a direct link versus going through the home page, then api list, then specific api.

Also, I need a playground to learn. Next might be something I use in an upcoming project. Figured its better to learn in a safe environment rather a high pressure client project.

**Comment by thedamian** [comment]
OH....and OH!
Ok. Approved!

**Comment by thedamian** [comment]
DENIED!!!!! DENIED!!!
:kissing:
Ok.... well at least we have the react routing taking care of (all 404's respond with index.html which allows https://sampleapis.com/api-list/avatar to work!
