### ISSUE TITLE
New Coffees

### ISSUE THREAD

**Issue by yaronchristiaens** [jermbo/SampleAPIs#148]
In the following API (https://api.sampleapis.com/coffee/hot) there have been added two new coffees (both with the title Black). Now there are 3 coffees who have exactly the same fields, except the id. Is this intentional? I have to build an own android app for school, but I can't get the data anymore, while previously I could get all the data. Now my coffee list returns 'null' in the app.

**Comment by jermbo** [comment]
Thank you for bringing this to our attention. 

The duplicated items are likely someone playing around with the api. These have been reset to the original data. 

As for why you are getting null in your project, it could be a number of reasons. The one that comes to mind is the rate limit. There is a limit of 500 requests for 5 minutes. Note, this number deducted from the same bucket on all apis in the system and all CRUD actions. If you reach that limit, you have to wait 5 minutes for it to reset. 

Double check how and when you are hitting the api endpoint. You might be running into an issue of trying to display data from the api when it might not be necessary.

Hope this helps. Good luck on your project.
