### ISSUE TITLE
API response includes errant name and rating avg values

### ISSUE THREAD

**Issue by 8dot5** [jermbo/SampleAPIs#152]
Hey guys, enjoying your API!

Thought it was worth pointing out that there's an issue with one of the beers.  

Doing a fetch of the Beers API (URL: https://api.sampleapis.com/beers/ale/). 

The first beer should be the Founder's Ale which has been correct up until last night. 

- The `name` key is returning an errant `a` value
- The `rating.average` is displaying a score of `9` out of the scale of 5.

```
{price: '$3', name: 'a', rating: {…}, image: 'https://www.totalwine.com/media/sys_master/twmmedia/h00/h94/11891416367134.png', id: 3}
id: 3
image: "https://www.totalwine.com/media/sys_master/twmmedia/h00/h94/11891416367134.png"
name: "a"
price: "$3"
rating: {average: 9, reviews: 298}
```

**Comment by jermbo** [comment]
Thanks for the love.

I have reset the APIs, so they should be back to normal.

Please be aware this is an open tool meant for learning. So there will be times that data is bad. There are bits of code in place to help enforce the shape of the object, as well as basic type checking, but given the very dynamic nature of these apis makes it a bit difficult and things are bound to fall through the cracks from time to time.
