### ISSUE TITLE
Inappropriate image URL in beers API

### ISSUE THREAD

**Issue by varunyn** [jermbo/SampleAPIs#157]
Please remove the following data from[ Beers API](https://sampleapis.com/api-list/beers). 

![SCR-20220726-fmo](https://user-images.githubusercontent.com/26843227/181057841-d5f610ff-33fc-4b4a-9f51-6eae97eec325.png)

**Comment by jermbo** [comment]
The APIs have been reset to correct data. Thank you for making us aware.
