### ISSUE TITLE
API List > Categories

### ISSUE THREAD

**Issue by ghost** [jermbo/SampleAPIs#163]
I'm not sure if this has been brought up, as I couldn't find it, or even if you are even still working on this project.

I found a specific thing in the All Categories, dropdown where all the options on the inside are white, and this is because of the .api-filter select{} in the CSS, where the var(--color-text-light) is used. I've found a quick fix that doesn't change what "All Categories" looks like besides in the dropdown. 

This fix is putting:
 ` option{ text-color: ----}`

Hopefully this helps!

**Comment by jermbo** [comment]
Closing this as it looks like the issue has been resolved.
