### ISSUE TITLE
Create API for blockchain projects

### ISSUE THREAD

**Issue by frederickalcantara** [jermbo/SampleAPIs#49]
Create a sample API for blockchain projects based on consensus, purpose behind it, market cap, ticker symbol, what languages it's written with, and how long it's been around for.

**Comment by thedamian** [comment]
Think of this project as a tricycle that helps you learn to ride a bike. There's no need to add a motor and an ability to more one of the wheels. It's not there to provide real APIs. but just to cut your teeth on HOW to access APIs from what ever project you are using. 

once you can show me you can bring in all the countries and their capitals then you can move on to pointing your project to your REAL target. Those tasty crypto currency numbers.
