### ISSUE TITLE
Countries JSON

### ISSUE THREAD

**Issue by jldorta** [jermbo/SampleAPIs#83]
I think the structure of https://github.com/jermbo/SampleAPIs/blob/main/src/api/countries.json should be different.

Instead of:
{
  "name": [
    { "BD": "Bangladesh" },
    { "BE": "Belgium" },
    { "BF": "Burkina Faso" },
    ...
  ],
  "capital": [
    { "BD": "Dhaka" },
    { "BE": "Brussels" },
    { "BF": "Ouagadougou" },
    ...
  ],
    ...
}

We should use:
{
  "name": [
    "BD": "Bangladesh" ,
    "BE": "Belgium" ,
    "BF": "Burkina Faso",
    ...
  ],
  "capital": [
      "BD": "Dhaka",
      "BE": "Brussels",
      "BF": "Ouagadougou",
    ...
  ],
    ...
}

It is going to be easy to manipulate and access to items inside the object.

If this makes any sense I can take care of it.

**Comment by jermbo** [comment]
Did you mean: 
```
{ 
  "name": {
    "BD": "Dhaka",
    "BE": "Brussels",
    ...
  },
  "capital": {
    "BD": "Dhaka",
    "BE": "Brussels",
    ...
  },
  ...
}
```

Your example uses an array, with object syntax and that will not work. I believe you meant to use an object instead of an array of objects. If I am reading that correctly, I agree that would be a little easier to access and reason about. 

Thank you for the suggestion. I'll look forward to your PR.

**Comment by thedamian** [comment]
I like this conversation but @jermbo @jldorta 
The question is would you want to access the object as:

CountryReply.us.population
or 

CountryReply.population.us

that would dictate how we rearrange this api.

**Comment by jermbo** [comment]
Good point. I understand why the original code was split into different categories, that was a decision by the original contributor. 

How I would have done this would be something like this:
```
{
  "countries": {
    "US": {
      "capital": "DC",
      "population": 1,
      "currency": "UDS",
      ...
    },
    ...
  }
}
```

or 

```
{
  "countries": [
    {
     "abbreviation": "US",
      "capital": "DC",
      "population": 1,
      "currency": "UDS",
      ...
    },
    ...
  ]
}
```

The difference is an object with the abbreviations as the key, versus an array of objects. They will all the same data, but packaged together. 

The pro of this approach is all the data you need is right there and you can shape the graphQL to the actual data you need. 

The con is.... less endpoints?
