### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by jermbo** [jermbo/SampleAPIs#91]
Now that the system is in a pretty stable place, I believe it would be a good time to start introducing some tests.

I am open for what tests should be there, but I think we need the following as an MVP:

* Ensure all .json files in the `api` folder have id's associated with each entry point. 
* Ensure all .json files in the `api` folder have at least 1 endpoint.
* Ensure all endpoints are included in the `apiList.js` file
  * Ensure all endpoints included have the minimum values. +
* Ensure all .json files in the `api` folder have associated backup file. `.json.backup`
* Ensure all endpoints are rendering.
* Ensure CRUD works on each endpoints.

+ `apiList.js` entry should have the following information 
```JavaScript
{
    id: 0, // Unique ID
    title: "", // Title to be displayed on home and individual pages
    longDesc: "", // A long description meant for display on the individual page. 
    desc: "", // A short description meant for display on the home page
    link: "", // Link to be used in the url. This should match the json file name exactly.
    graphLink: "", // The same name as the link, but with a '/graphql' in at the end.  
    endPoints: [ "" , ... ], // list of available endpoints, in string format. 
},
```

**Comment by jonathans199** [comment]
@jermbo i've added one test to get started 
https://github.com/jermbo/SampleAPIs/pull/92

let me know if that's a good start
